/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.Provider;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Order.OrderItem;
import Business.Organization.DesignerOrganization;
import Business.Organization.Organization;
import Business.Organization.ProviderOrganization;
import Business.Products.Product;
import Business.Products.ProductDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ProvoiderRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aashrith
 */
public class AddAProductPanel extends javax.swing.JPanel {

    
    private ProductDirectory prod;
     EcoSystem system ;
    JPanel userProcessContainer;
    //DB4OUtil dB4OUtil;
    Enterprise enterprise;
     UserAccount account;
    

   


  

    AddAProductPanel(JPanel userProcessContainer, DB4OUtil dB4OUtil, Enterprise enterprise, UserAccount account, EcoSystem system) {
    //    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
       this.userProcessContainer = userProcessContainer;
      // this.dB4OUtil = dB4OUtil;
       this.enterprise = enterprise;
       this.account = account;
      this.system = system;
        populateComboBox();
        populateComboBox2();
        fullscreen();
    
    }
    
    public void fullscreen(){
       int width = Toolkit.getDefaultToolkit().getScreenSize().width;
       int heigth = Toolkit.getDefaultToolkit().getScreenSize().height;
       jLabel4.setSize(width, heigth);
   }
    
    public void populateComboBox()
    {
        DefaultComboBoxModel dcm = (DefaultComboBoxModel) pNameComboBox.getModel();
        
        for(Product p :system.getProductDirectory().getProductList())
        {
            pNameComboBox.addItem(p.getProdName());
        }
        
    }
    
    public void populateComboBox2()
    {
       
        for(Product p :system.getProductDirectory().getProductList())
        {
            productTypeComboBox.addItem(p.getProdType());
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qtyTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pNameComboBox = new javax.swing.JComboBox();
        productTypeComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(null);

        qtyTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qtyTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyTextFieldKeyTyped(evt);
            }
        });
        add(qtyTextField);
        qtyTextField.setBounds(240, 140, 170, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quantity:");
        add(jLabel1);
        jLabel1.setBounds(130, 130, 90, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Name:");
        add(jLabel2);
        jLabel2.setBounds(80, 50, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Type:");
        add(jLabel3);
        jLabel3.setBounds(90, 90, 130, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Send Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(210, 220, 170, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(20, 380, 130, 31);

        pNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CupBoard", "Bed Frame", "TV Unit", "Racks", "Decorative Overlays" }));
        add(pNameComboBox);
        pNameComboBox.setBounds(240, 50, 170, 30);

        productTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mahogany", "Maple-nut Wood", "Pine Wood", "Iron Wood" }));
        add(productTypeComboBox);
        productTypeComboBox.setBounds(240, 100, 170, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\ajju\\tree_lined_street-wallpaper-1920x1080.jpg")); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(0, 0, 660, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String prodName = (String) pNameComboBox.getSelectedItem();
        String prodType = (String) productTypeComboBox.getSelectedItem();
         int Qty =  Integer.parseInt(qtyTextField.getText());
       
        
        if(prodName.equalsIgnoreCase("")||prodName.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter some values");
        }
        
        else
        {
        
         ProvoiderRequest wr = new ProvoiderRequest();
       
         wr.getProduct().setProdName(prodName);
         wr.getProduct().setProdType(prodType);
         wr.getProduct().setQuantity(Qty);
         wr.setSender(account);
         wr.setStatus("Pending");
         
         
         Organization organization = null;
         
        for( Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
        {
           // System.err.println(enterprise.getName());
            if(org instanceof DesignerOrganization)
            {
                organization = org;
                break;
            }
        }
        
        if(organization!= null)
        {
            organization.getWorkQueue().getWorkRequestList().add(wr);
            account.getWorkQueue().getWorkRequestList().add(wr);
            
        }
        JOptionPane.showMessageDialog(null,"Request sent to Designer");
         
         
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProviderWorkAreaPanel pwa = (ProviderWorkAreaPanel) component;
        pwa.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void qtyTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTextFieldKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       if(!Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE){
           evt.consume();
           JOptionPane.showMessageDialog(null,"Please enter only numerics");
       }
    }//GEN-LAST:event_qtyTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox pNameComboBox;
    private javax.swing.JComboBox productTypeComboBox;
    private javax.swing.JTextField qtyTextField;
    // End of variables declaration//GEN-END:variables
}
