/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    Enterprise enterprise;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(JPanel userProcessContainer,OrganizationDirectory directory,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.directory = directory;
        this.enterprise = enterprise;
        fullscreen();
        populateTable();
        populateCombo();
    }
    
    public void fullscreen(){
       int width = Toolkit.getDefaultToolkit().getScreenSize().width;
       int heigth = Toolkit.getDefaultToolkit().getScreenSize().height;
       jLabel2.setSize(width, heigth);
   }
    
    private void populateCombo(){
        if(enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Banking"))
        {
        organizationJComboBox.removeAllItems();
        for (Type type : Organization.Type.values() ){
            if (!type.getValue().equals(Type.Admin.getValue()) && !type.getValue().equals(Type.Ecoguard.getValue()) 
                && !type.getValue().equals(Type.HR.getValue()) && !type.getValue().equals(Type.Realtor.getValue())
                && !type.getValue().equals(Type.BudgetAllocation.getValue()))
                organizationJComboBox.addItem(type);
        }
        }
        else if(enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Corporate"))
        {
        organizationJComboBox.removeAllItems();
        for (Type type : Organization.Type.values() ){
            if (!type.getValue().equals(Type.Admin.getValue()) && !type.getValue().equals(Type.Ecoguard.getValue()) 
                && !type.getValue().equals(Type.FinanceOffice.getValue()) && !type.getValue().equals(Type.Realtor.getValue())
                && !type.getValue().equals(Type.BudgetAllocation.getValue()))
                organizationJComboBox.addItem(type);
        }
        }
        else if(enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Education"))
        {
        organizationJComboBox.removeAllItems();
        for (Type type : Organization.Type.values() ){
            if (!type.getValue().equals(Type.Admin.getValue()) && !type.getValue().equals(Type.Ecoguard.getValue()) 
                && !type.getValue().equals(Type.FinanceOffice.getValue()) && !type.getValue().equals(Type.Realtor.getValue())
                && !type.getValue().equals(Type.HR.getValue()))
                organizationJComboBox.addItem(type);
        }
        }
        else if(enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Housing"))
        {
        organizationJComboBox.removeAllItems();
        for (Type type : Organization.Type.values() ){
            if (!type.getValue().equals(Type.Admin.getValue()) && !type.getValue().equals(Type.Ecoguard.getValue()) 
                && !type.getValue().equals(Type.FinanceOffice.getValue()) && !type.getValue().equals(Type.BudgetAllocation.getValue())
                && !type.getValue().equals(Type.HR.getValue()))
                organizationJComboBox.addItem(type);
        }
        }
    }

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
        
        model.setRowCount(0);
        
        for (Organization organization : directory.getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        addJButton = new javax.swing.JButton();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJTable);
        if (organizationJTable.getColumnModel().getColumnCount() > 0) {
            organizationJTable.getColumnModel().getColumn(0).setResizable(false);
            organizationJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(111, 60, 620, 110);

        addJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addJButton.setText("Add Organization");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton);
        addJButton.setBounds(320, 300, 187, 31);

        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });
        add(organizationJComboBox);
        organizationJComboBox.setBounds(450, 230, 180, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Organization Type ");
        add(jLabel1);
        jLabel1.setBounds(230, 230, 169, 22);

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(60, 400, 111, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/landscape.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 910, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

        Type type = (Type) organizationJComboBox.getSelectedItem();
        directory.createOrganization(type);
        populateTable();
        JOptionPane.showMessageDialog(null,"Organization successfully added");
    }//GEN-LAST:event_addJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTable organizationJTable;
    // End of variables declaration//GEN-END:variables
}
