/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.Designer;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DesignerOrganization;
import Business.Organization.Organization;
import Business.Organization.ProviderOrganization;
import Business.Organization.SupplierOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ProvoiderRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.CardPanel;
import java.awt.CardLayout;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class DesignerWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    //DB4OUtil dB4OUtil;
    Enterprise enterprise;
    //  EcoSystem system = EcoSystem.getInstance();
    DB4OUtil dB4OUtil;
    EcoSystem system;
    private DesignerOrganization organization;
    //  DB4OUtil dB = DB4OUtil.getInstance();

    public DesignerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DB4OUtil dB4OUtil, Enterprise enterprise, EcoSystem business, Organization organization) {
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.dB4OUtil = dB4OUtil;
        this.organization = (DesignerOrganization) organization;
        this.account = account;
        this.system = business;
        this.enterprise = enterprise;
        populateTable();
        fullscreen();
    }
    
    public void fullscreen(){
       int width = Toolkit.getDefaultToolkit().getScreenSize().width;
       int heigth = Toolkit.getDefaultToolkit().getScreenSize().height;
       jLabel1.setSize(width, heigth);
   }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) ProductTable1.getModel();
        dtm.setRowCount(0);

        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
            
            Object[] row = new Object[8];
            row[0] = wr;
            row[1] = wr.getProduct().getProdType();
            row[2] = wr.getSender().getEmployee();
            row[3] = wr.getReceiver() == null ? null : wr.getReceiver().getEmployee().getName();
            row[4] = wr.getProduct().getQuantity();
            row[5] = wr.getStatus();
            dtm.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(null);

        ProductTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Product Type", "Sender", "Receiver", "Quantity", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ProductTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(90, 270, 850, 148);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Assign to Me");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(330, 540, 145, 31);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(50, 730, 95, 31);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(550, 540, 130, 30);

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel2.setText("Designer Work Area");
        add(jLabel2);
        jLabel2.setBounds(380, 80, 320, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Designer/wallpaper-yellow-trees.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -10, 1200, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int selectedrow = ProductTable1.getSelectedRow();
        if (selectedrow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;

        }
        WorkRequest request = (WorkRequest) ProductTable1.getValueAt(selectedrow, 0);
        request.setReceiver(account);
        request.setStatus("Assigned to Manager");
        populateTable();
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CardPanel cardPanel = new CardPanel(userProcessContainer, system, dB4OUtil);
        userProcessContainer.add("Login Screen", cardPanel);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);

        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       int selectedRow = ProductTable1.getSelectedRow();

       if (selectedRow < 0) {
           JOptionPane.showMessageDialog(null, "Please select a row to continue");
           return;
       }

       ProvoiderRequest wr = (ProvoiderRequest) ProductTable1.getValueAt(selectedRow, 0);
       if(wr.getStatus().equalsIgnoreCase("Pending"))
       {
          JOptionPane.showMessageDialog(null,"You need to ASSIGN First!!");
       }
       else  
       {
       String prodName = String.valueOf(ProductTable1.getValueAt(selectedRow, 0));
       String prodType = (String) ProductTable1.getValueAt(selectedRow, 1);
       int quantity = Integer.parseInt(ProductTable1.getValueAt(selectedRow, 4).toString());
       
       SearchJPanel1 panel = new SearchJPanel1(userProcessContainer,system,prodName,prodType,quantity,dB4OUtil,wr,enterprise);
       userProcessContainer.add("SearchJPanel", panel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
       }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProductTable1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
