/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.Ecoguard;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Order.OrderItem;
import Business.UserAccount.UserAccount;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Locale;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author anand
 */
public class EcoguardSelfAnalysis extends javax.swing.JPanel {

    /**
     * Creates new form EcoguardSelfAnalysis
     */
    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    EcoSystem system;
    DB4OUtil dB4OUtil;
    
    public EcoguardSelfAnalysis() {
        initComponents();
    }

    EcoguardSelfAnalysis(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem system, DB4OUtil dB4OUtil) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
        pieChart();
        populateTable();
    }

    
        public void populateTable() {

        DefaultTableModel dtm = (DefaultTableModel) contributionTable.getModel();
        for (Network network : system.getNetworkList()) {
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
           //     for (OrderItem oi : e.getOrder().getOrderItemList()) {
                //    if(oi.getOrderStatus().equalsIgnoreCase("Approved")){
                        Object[] row = new Object[10];
                        row[0] = e.getName();
                        row[1] = e.getContribution();
                        dtm.addRow(row);
                   // }
                //}
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pieCHartPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contributionTable = new javax.swing.JTable();
        bckBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout pieCHartPanelLayout = new javax.swing.GroupLayout(pieCHartPanel);
        pieCHartPanel.setLayout(pieCHartPanelLayout);
        pieCHartPanelLayout.setHorizontalGroup(
            pieCHartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        pieCHartPanelLayout.setVerticalGroup(
            pieCHartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        contributionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise", "Contribution"
            }
        ));
        jScrollPane1.setViewportView(contributionTable);

        bckBtn.setText("<<BACK");
        bckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GO GREEN BY ECO GUARD AND CONTRIBUTIONS BY ENTERPRISES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(bckBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(pieCHartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1347, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(pieCHartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addComponent(bckBtn)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pieChart(){
        DefaultPieDataset dataset = new DefaultPieDataset();  
       int success = 0;
       int fail = 0;
        
        for(Network n: system.getNetworkList()){
            for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                for(OrderItem oi:e.getOrder().getOrderItemList()){
                    if(oi.getFinalStatus() != null){
                        if(oi.getFinalStatus().equalsIgnoreCase("Success")){
                            success++;
                        }else{
                            fail++;
                        }
                    }
                }
            }
        }
        
       dataset.setValue("Converted Go Green", success);        
       dataset.setValue("Will be converted to Green soon", fail);        
       
       JFreeChart jChart = ChartFactory.createPieChart3D("Mobile Sales", dataset, true, true, Locale.ITALY);
       jChart.setBackgroundPaint(Color.ORANGE);
       PiePlot plot = (PiePlot) jChart.getPlot();
       plot.setSectionPaint("Converted Go Green", Color.green.darker());
       plot.setSectionPaint("Will be converted to Green soon", Color.red.darker());
     //  plot.setSectionPaint(fail, paint);
      // plot.set
       //ChartFrame jframe = new ChartFrame("Aash", jChart);
       
//       final PiePlot3D plot = (PiePlot3D) jChart.getPlot();
//        plot.setStartAngle(270);
//        plot.setDirection(Rotation.ANTICLOCKWISE);
//        plot.setForegroundAlpha(0.60f);
//        plot.setInteriorGap(0.33);
        
        final Rotator rotator = new Rotator((PiePlot3D) plot);
        rotator.start();
       
        ChartPanel pieCHart = new ChartPanel(jChart);
        pieCHartPanel.removeAll();
        pieCHartPanel.setLayout(new BorderLayout());
        pieCHartPanel.add(pieCHart,BorderLayout.CENTER);
        pieCHartPanel.validate();

    }
    
    private void bckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_bckBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bckBtn;
    private javax.swing.JTable contributionTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pieCHartPanel;
    // End of variables declaration//GEN-END:variables
}
