/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.Ecoguard;

import Business.EcoSystem;
import Business.Order.OrderItem;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Image;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.property.HorizontalAlignment;

import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.imageio.ImageIO;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartRenderingInfo;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.entity.StandardEntityCollection;


/**
 *
 * @author Aashrith
 */
public class EJPanel extends javax.swing.JPanel {

   
    
   JFreeChart barChart;
   JFreeChart areaChart;
   private JPanel userProcessContainer; 
   EcoSystem system;
   OrderItem orderItem;
   
   
    

    EJPanel(JFreeChart barchart, JFreeChart areachart, JPanel userProcessContainer,EcoSystem system,OrderItem orderItem) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
               initComponents();
        this.barChart = barchart;
        this.areaChart = areachart;
        this.system = system;
        this.orderItem = orderItem;
        this.userProcessContainer = userProcessContainer;
        populatePanel();
    }
    
    public void fullscreen(){
        Dimension width = Toolkit.getDefaultToolkit().getScreenSize().getSize();
       // JPanel.
    }
    public void populatePanel()
    {
        
        ChartPanel barPanel = new ChartPanel(barChart);
        barChartPanel.removeAll();
        barChartPanel.setLayout(new BorderLayout());
        barChartPanel.add(barPanel,BorderLayout.CENTER);
        barChartPanel.validate();
        
               
        ChartPanel areaPanel = new ChartPanel(areaChart);
        areaChartpanel.removeAll();
        areaChartpanel.setLayout(new BorderLayout());
        areaChartpanel.add(areaPanel,BorderLayout.CENTER);
        areaChartpanel.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public String convertToPdf(){
      //   String logoLoc = "C:\\Users\\anand\\Desktop\\Aed Final 2\\FinalProject2017_AED\\src\\PDF\\ecoguard_logo1.png"; 
//         String barChartLoc = "C:\\Users\\anand\\Desktop\\Aed Final 2\\FinalProject2017_AED\\Barchart.png";
//         String areaChartLoc = "C:\\Users\\anand\\Desktop\\Aed Final 2\\FinalProject2017_AED\\Areachart.png";
//         String fileLoc = "C:\\Users\\anand\\Desktop\\Aed Final 2\\FinalProject2017_AED\\src\\PDF\\EcoGuard.pdf";

            String classpathStr = System.getProperty("java.class.path");
            System.out.println(classpathStr);
//         
            URL url = getClass().getResource("ecoguard_logo1.png");
            //String pt = getClass().getResource("/Business/PDF/ecoguard_logo1.png").getPath();
            //String pt1 = getClass().getResource("Ecoguard/ecoguard_logo1.png").getPath();
//            BufferedImage image = null;
//       try {
//           image = ImageIO.read(url);
//       } catch (IOException ex) {
//           Logger.getLogger(EJPanel.class.getName()).log(Level.SEVERE, null, ex);
//       }
//         
        final File fileEco = new File("EcoGuard.pdf");
        final File fileBar = new File("Barchart.png");
        final File fileArea = new File("Areachart.png");
        

        try {
            final ChartRenderingInfo info = new ChartRenderingInfo(new StandardEntityCollection());
            final ChartRenderingInfo info1 = new ChartRenderingInfo(new StandardEntityCollection());

            ChartUtilities.saveChartAsJPEG(fileArea, areaChart, 600, 400, info);
            ChartUtilities.saveChartAsJPEG(fileBar, barChart, 600, 400, info1);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
         
        try {
            FileOutputStream fos = new FileOutputStream(fileEco.getAbsolutePath());
             PdfWriter writer = new PdfWriter(fos);
             PdfDocument pdf =  new PdfDocument(writer);
             Document doc = new Document(pdf);
             Paragraph p = new Paragraph("The analysis of your orderList and usage of Suggested product outcome will lead you more profit.");
             Paragraph p1 = new Paragraph("This Graph tells the ratio of Profit of orders made by your enterprise in last Five years if you have used the suggested Eco friendly resources for your goods");
             Paragraph p3 = new Paragraph("This Graph tells you the ratio of usage of woods VS Bamboo as per regenration factor");
             Paragraph p4 = new Paragraph("Our Eco Friendly website is : green-clique.appspot.com");
             Paragraph p5 = new Paragraph();
             Paragraph p6 = new Paragraph();
             Paragraph p2 = new Paragraph(pdfCotentArea.getText());
             Image ecoGuardLogo;
             Image barChart = null;
             Image areaChart = null;
             Image logo = null;
             try {
                    ecoGuardLogo = new Image(ImageDataFactory.create(url));
                    ecoGuardLogo.scaleAbsolute(50, 0);
                    ecoGuardLogo.setHorizontalAlignment(HorizontalAlignment.CENTER);
                    ecoGuardLogo.scaleToFit(400, 200);
                    doc.add(ecoGuardLogo);   
                    
                    barChart = new Image(ImageDataFactory.create(fileBar.getAbsolutePath()));
                    //barChart.scaleToFit(700, 200);
                    barChart.setWidthPercent(100);
                    barChart.setHeight(400);
                    p5.add(barChart);
                    
                    areaChart = new Image(ImageDataFactory.create(fileArea.getAbsolutePath()));
                    //barChart.scaleToFit(700, 200);
                    areaChart.setWidthPercent(100);
                    areaChart.setHeight(400);
                    p6.add(areaChart);
                    
                    
                    
             } catch (MalformedURLException ex) {   
                 Logger.getLogger(EJPanel.class.getName()).log(Level.SEVERE, null, ex);
             }
             doc.add(p);
             //p1.add(barChart);
             doc.add(p1);
             doc.add(p5);
             doc.add(p2);
             doc.add(p6);
             doc.add(p3);
             doc.add(p4);
             doc.close();
             JOptionPane.showMessageDialog(null, "PDF Created");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(EJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
         return fileEco.getAbsolutePath();
    }
    
     public void emailFunction(){
    
        Properties prop = new Properties();
        prop.put("mail.smtp.user","ecoguardsystems@gmail.com");
        prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "465");
        
        prop.put("mail.smtp.starttls.enable","true");
        prop.put("mail.smtp.debug", "true");
        
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.socketFactory.port","465"); //its mentioned in java site for SSL port is 465 for ssl
        prop.put("mail.smtp.socketFactory.Class", "javax.net.ssl.SSLSocketFactory");
        
        
        
        Session session = Session.getDefaultInstance(prop,
                new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication("ecoguardsystems@gmail.com", "ecoguard123");
                }
                }
                );
           try{
                Message mess = new MimeMessage(session);
                mess.setFrom(new InternetAddress("ecoguardsystems@gmail.com"));
                mess.setRecipients(Message.RecipientType.TO, InternetAddress.parse("anandganesh.bala@gmail.com,aashrith95@gmail.com,dawna14@gmail.com"));
                mess.setSubject("Order Suggestion From Ecoguard");
               // mess.setText("Test mail from Ecoguard");
                //Transport.send(mess);
                
                //Attachment
                MimeBodyPart msgBodyPart = new MimeBodyPart();
                msgBodyPart.setText(pdfCotentArea.getText());
                Multipart multiPart = new MimeMultipart();
                
                String fileAbPath = convertToPdf();
               // String filepath = "C:\\Users\\anand\\Desktop\\Aed Final 2\\FinalProject2017_AED\\src\\PDF\\EcoGuard.pdf";
                
                MimeBodyPart msgBodyPart2 = new MimeBodyPart();
                DataSource src = new FileDataSource(fileAbPath);
                msgBodyPart2.setDataHandler(new DataHandler(src));
                msgBodyPart2.setFileName("Ecoguard Analysis.pdf");
               
                multiPart.addBodyPart(msgBodyPart);
                multiPart.addBodyPart(msgBodyPart2);

                mess.setContent(multiPart);

                Transport transport = session.getTransport("smtps");
                transport.connect("smtp.gmail.com", Integer.valueOf("465"), "ecoguardsystems@gmail.com", "ecoguard123");
                transport.sendMessage(mess, mess.getAllRecipients());
                transport.close();
                
                
                JOptionPane.showMessageDialog(null, "Mail Sent");
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barChartPanel = new javax.swing.JPanel();
        areaChartpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        emailContentarea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pdfCotentArea = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setLayout(null);

        javax.swing.GroupLayout barChartPanelLayout = new javax.swing.GroupLayout(barChartPanel);
        barChartPanel.setLayout(barChartPanelLayout);
        barChartPanelLayout.setHorizontalGroup(
            barChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        barChartPanelLayout.setVerticalGroup(
            barChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        add(barChartPanel);
        barChartPanel.setBounds(143, 100, 476, 236);

        javax.swing.GroupLayout areaChartpanelLayout = new javax.swing.GroupLayout(areaChartpanel);
        areaChartpanel.setLayout(areaChartpanelLayout);
        areaChartpanelLayout.setHorizontalGroup(
            areaChartpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        areaChartpanelLayout.setVerticalGroup(
            areaChartpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        add(areaChartpanel);
        areaChartpanel.setBounds(143, 450, 476, 252);

        jLabel2.setText("From :");
        add(jLabel2);
        jLabel2.setBounds(670, 120, 107, 26);

        jLabel4.setText("Eco Guard");
        add(jLabel4);
        jLabel4.setBounds(790, 120, 443, 26);

        jLabel5.setText("Order sent by");
        add(jLabel5);
        jLabel5.setBounds(790, 180, 443, 26);

        jLabel1.setText("To :");
        add(jLabel1);
        jLabel1.setBounds(670, 180, 107, 26);

        jLabel6.setText("Subject :");
        add(jLabel6);
        jLabel6.setBounds(670, 230, 107, 26);
        add(jTextField1);
        jTextField1.setBounds(790, 230, 444, 26);

        jLabel3.setText("Email Content :");
        add(jLabel3);
        jLabel3.setBounds(660, 290, 110, 26);

        emailContentarea.setColumns(20);
        emailContentarea.setRows(5);
        jScrollPane2.setViewportView(emailContentarea);

        add(jScrollPane2);
        jScrollPane2.setBounds(790, 290, 444, 136);

        jLabel7.setText("Specific Content :");
        add(jLabel7);
        jLabel7.setBounds(650, 460, 124, 26);

        pdfCotentArea.setColumns(20);
        pdfCotentArea.setRows(5);
        jScrollPane1.setViewportView(pdfCotentArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(790, 460, 444, 136);

        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(930, 660, 121, 42);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(30, 740, 65, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        emailFunction();
        orderItem.setOrderStatus("Email Sent By EcoGuard");
        JOptionPane.showMessageDialog(null, "Email sent with Analysis attachment");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel areaChartpanel;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel barChartPanel;
    private javax.swing.JTextArea emailContentarea;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea pdfCotentArea;
    // End of variables declaration//GEN-END:variables
}
